engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslintrc.js
      extensions:
      - .js
ratings:
  paths:
  - "**.js"
  exclude_paths:
  - "lib/"
