sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "6"
      env: TASK=browser
cache:
  directories:
  - node_modules
script:
  - make ${TASK}
env:
  # See how to get encrypted env variables for saucelabs here:
  # https://docs.travis-ci.com/user/sauce-connect/
  global:
    # travis encrypt SAUCE_USERNAME=futil
    - secure: "intAImWiGH3IyrtSghpK8EarKekOCOtEClVQwkKKtPa4vyJ1AtxRfSbsSqaWP8XxDG24eqca6rEPBETrTALyQPNFZZGk/+9f5eO5fqm1BRV5aghEJdKmLVxi+iBn5VLnwru3EI11EnNMZBobMPjJDIiRo7lLRuMizSWy1koAHVjeNGu+UQWEafNcU0n/kja9/nmwidrB5dBrGRuazkkQSxIWxpi2SvZNPCI6tUKcVqldkn/jjlTDr01+BtRtVUtn8M2IsufB/+cXCtsSyBo3DQTzZof91LSxB5ywhTANipB2xP+6dGoUaPbuefxhfaHsnm9mkRuWyUrMLizQR/jbu5CR37Yh0VS29cjPFT3coWi3c7LdzfuahSAFF9KLT+66C/j7gnJ9UKPGSoW+B+sXq5t9T8rWBLe6gX3L13P6Xh1VtpSIc4OjPlKj0b5VahS49kDkgGhrcDUkkpVH/ajgCgN/ZVuc93jp1kvBitKJEGj0DRrk7Oe8mxpcDCelY0dasq4qg40A/C8X1T70lSbDbCiVe1sIChIe6Y/m49/QmnCEI3vjMbnXMQxP9gtFFHrTxu77Qi+vB2Rezmt9PvtrbPIucHZTB+mqdJEKF0aNrJduli3UhSK2bh96WUbDB4yGIIPz0HM2OEVh913T8qRckFmOLoxnPizwT9BqN1uHt5w="
    # travis encrypt SAUCE_ACCESS_KEY=YOUR_KEY_HERE
    - secure: "bL2ciMHRZn7CckuhQoNPxgZkZSG5HqLk3OdRjc9x741VZS+KJ4LL3PngaBT3LQFgp4LzWge9dIJKNlXGcW7WNOAXsvkjnfMtRfgOj/DSpiKtKjgwt8P/Mt8m4QuUvsQPPRipWDO6FX6XJxzeNTmz65MiLa5iz6WQsm09opQgccLUKjzQHD11XqjxUBZyCa5xoVoEI7H8WlbFwFaF0SqwtO2mTEVbOXZx2+WvvRdYK60+VXd7lywMWK4lj3FGO5No/V2h7NjzH8DtLLNr9aTp+fNJjqAYh/8/cHZnLaZBLQ4pqtw2jUfDdmK4RRVo7XT1wHh3DHNXJXvpKjQkdFGbvIT8VyvdczoB6xywbNXTSXn2TpMPzoaPVhewJp/aFyedoYjreW/oDbgZykpP+zVfLcm370zUg/u0sFR5mjQ3DWJV6jS/vB+q1SIXB9R4jwan/tmC+os+iVhYwb8DFNMzKUIEM82sa/QOUv3nK0lEXPqOgS7f+4OWK+73XTgFn5SZeYgld1IVPfFzvk4YhJVLFCCLXn7qS8ysA3gWuQJnRjU/0RVgY0q8UURzZPGsIDYW6EBNTGavCouFxzB8SBqzN1LYI/3lTyBYxct8hwYpXkW0fuqI41VKXkXU41JrdNC/zwJ+aUFvl6HaLL0vb669nWVPPtHCwfoRg/EhQ2ScTCg="
