sudo: false
language: node_js
node_js:
- 'node'
cache:
  directories:
    - node_modules
notifications:
  email: false
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_KEY
  skip_cleanup: true
  on:
    branch: master
after_script:
    - npm run cicoverage | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    - npm run cicoverage | ./node_modules/.bin/codacy-coverage
